#!/usr/bin/env python3
"""
Example: Automated Clio File Upload Demo

This script demonstrates how to use the Clio file upload functionality
in an automated workflow. It shows how you might integrate file uploads
into your existing applications.

Use Case: Automatically upload generated PDF documents to Clio after creation
"""

import os
import sys

# Example: Generate a sample document
def create_sample_document(filename="sample_invoice.txt"):
    """
    Create a sample document for demonstration
    In a real scenario, this might be a PDF generated by the HTML-to-PDF API
    """
    content = """
    INVOICE #12345
    
    Date: 2025-12-26
    Client: Sample Client
    
    Services Rendered:
    - Legal Consultation (2 hours) - $500.00
    - Document Review (1 hour) - $250.00
    
    Total: $750.00
    
    Payment Due: 2025-01-25
    """
    
    with open(filename, 'w') as f:
        f.write(content)
    
    print(f"✓ Created sample document: {filename}")
    return filename


def demo_basic_upload():
    """
    Demo 1: Basic file upload
    """
    print("\n" + "="*60)
    print("Demo 1: Basic File Upload")
    print("="*60)
    
    # Create a sample file
    filename = create_sample_document()
    
    print("\nTo upload this file to Clio, run:")
    print(f"  python clio_upload.py --file {filename}")
    
    # Clean up
    if os.path.exists(filename):
        os.remove(filename)
        print(f"\n✓ Cleaned up: {filename}")


def demo_upload_with_matter():
    """
    Demo 2: Upload and attach to a matter
    """
    print("\n" + "="*60)
    print("Demo 2: Upload with Matter Attachment")
    print("="*60)
    
    filename = create_sample_document("contract_review.txt")
    
    print("\nTo upload and attach to a specific matter, run:")
    print(f"  python clio_upload.py --file {filename} --matter 12345")
    
    print("\nFirst, find your matter ID:")
    print("  python clio_upload.py --list-matters")
    
    # Clean up
    if os.path.exists(filename):
        os.remove(filename)
        print(f"\n✓ Cleaned up: {filename}")


def demo_programmatic_upload():
    """
    Demo 3: Programmatic upload using the ClioFileUploader class
    """
    print("\n" + "="*60)
    print("Demo 3: Programmatic Upload (Python API)")
    print("="*60)
    
    print("\nYou can also use the ClioFileUploader class in your Python code:")
    print("""
from clio_upload import ClioFileUploader

# Initialize uploader
uploader = ClioFileUploader(config_path='.clio-config.json')

# Upload a file
response = uploader.upload_file(
    file_path='document.pdf',
    matter_id=12345,
    name='Custom Document Name'
)

print(f"Upload successful: {response}")

# List recent documents
documents = uploader.list_recent_documents(limit=10)
for doc in documents:
    print(f"- {doc.get('name')} (ID: {doc.get('id')})")
    """)


def demo_integration_workflow():
    """
    Demo 4: Integration with HTML-to-PDF workflow
    """
    print("\n" + "="*60)
    print("Demo 4: Integration with HTML-to-PDF API")
    print("="*60)
    
    print("\nComplete workflow example:")
    print("""
1. Generate PDF from HTML using the HTML-to-PDF API
2. Save the PDF locally
3. Upload to Clio with the clio_upload.py script

Example Python code:

import requests
from clio_upload import ClioFileUploader

# Step 1: Generate PDF from HTML
response = requests.post(
    'http://localhost:5000/convert',
    headers={'X-API-Key': 'your-api-key'},
    json={
        'html': '<html><body><h1>Invoice</h1></body></html>',
        'filename': 'invoice.pdf'
    }
)

# Step 2: Save PDF
with open('invoice.pdf', 'wb') as f:
    f.write(response.content)

# Step 3: Upload to Clio
uploader = ClioFileUploader()
result = uploader.upload_file(
    file_path='invoice.pdf',
    matter_id=12345,
    name='Client Invoice #12345'
)

print(f"PDF generated and uploaded to Clio: {result}")
    """)


def demo_batch_upload():
    """
    Demo 5: Batch file upload
    """
    print("\n" + "="*60)
    print("Demo 5: Batch Upload Multiple Files")
    print("="*60)
    
    print("\nExample code for uploading multiple files:")
    print("""
from clio_upload import ClioFileUploader
import os

uploader = ClioFileUploader()

files_to_upload = [
    'contract.pdf',
    'invoice.pdf',
    'receipt.pdf'
]

for file_path in files_to_upload:
    if os.path.exists(file_path):
        print(f"Uploading {file_path}...")
        try:
            result = uploader.upload_file(
                file_path=file_path,
                matter_id=12345
            )
            print(f"✓ Uploaded: {file_path}")
        except Exception as e:
            print(f"✗ Failed: {file_path} - {e}")
    """)


def main():
    """
    Run all demos
    """
    print("\n" + "="*70)
    print(" Clio File Upload - Usage Examples & Demos")
    print("="*70)
    
    print("\nThis script demonstrates various ways to use the Clio file upload")
    print("functionality. These are examples only - you'll need to configure")
    print("your Clio credentials first.\n")
    
    print("Setup Instructions:")
    print("1. Copy .clio-config.example.json to .clio-config.json")
    print("2. Add your Clio access token to .clio-config.json")
    print("3. Run the examples below\n")
    
    # Run demos
    demo_basic_upload()
    demo_upload_with_matter()
    demo_programmatic_upload()
    demo_integration_workflow()
    demo_batch_upload()
    
    print("\n" + "="*70)
    print("📚 For more information, see CLIO_UPLOAD_README.md")
    print("="*70 + "\n")


if __name__ == '__main__':
    main()
